#!/bin/sh

# Use neovim for vim if present.
# command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"
command -v nvim >/dev/null && alias vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	yt="youtube-dl -o '%(title)s.%(ext)s' --add-metadata -i " \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
# ls="ls -hN --color=auto --group-directories-first" \
alias \
	ls="exa --icons --group-directories-first" \
	la="exa --icons --group-directories-first -la" \
	grep="grep --color=auto" \
	free="free -h" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	dosbox="dosbox -conf "$XDG_CONFIG_HOME"/dosbox/dosbox.conf" \
	z="zathura" \
	mocp="mocp -M "$XDG_CONFIG_HOME"/moc" \
	gdot="/usr/bin/git --git-dir=$XDG_CONFIG_HOME/dotfiles/ --work-tree=$HOME" \
	cap="flameshot gui"

alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"

alias \
	upd="pikaur -Syu" \
	setup="sudo pacman -S" \
	upd-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg" \
	errors="journalctl -p 3 -xb" \
	remove="sudo pacman -Rns" \
	bpp="pacman -Qq | fzf --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(pacman -Qil {} | less)'" \
	mirrors="sudo reflector --verbose --latest 25 --sort rate --save /etc/pacman.d/mirrorlist"
